{% set name = "qforce" %}
{% set version = "0.6.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qforce-{{ version }}.tar.gz
  sha256: 68558b2c9c5486b6ffa0ffd007dbfba93edc4787ac3b31af64a722342bd8968a

build:
  entry_points:
    - qforce=qforce.main:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - scipy
    - numpy
    - ase
    - matplotlib-base
    - seaborn
    - networkx
    - pulp <2.2
    - numba >=0.50
    - pycolt >=0.5.3

test:
  imports:
    - qforce
  commands:
    - pip check
    - qforce --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/selimsami/qforce
  summary: 'Q-Force: Quantum mechanically augmented molecular force fields'
  license: Apache-2.0
  license_file: LICENCE

extra:
  recipe-maintainers:
    - jan-janssen
